services:
  py-proxy:
    build: .
    image: py-proxy:latest
    network_mode: host
    restart: unless-stopped
    volumes:
      - /opt/py_proxy/config.json:/opt/py_proxy/config.json:ro
      # Pas onderstaande paden aan aan de locatie van je TLS-certs:
      - /home/admin/ssl:/home/admin/ssl:ro
